Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tickets.Models;

namespace tickets.Controllers
{
    public class TeamsController : Controller
    {
        private ticketsEntities db = new ticketsEntities();

        // GET: Teams
        public ActionResult Index()
        {
            return View(db.Team.ToList());
        }

        
        // GET: Teams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Team.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            List<Match> matches_fitrst_team = db.Match.Where(t => t.firts_team == id).ToList();
            List<Match> matches_second_team = db.Match.Where(t => t.second_team == id).ToList();
            foreach(var item in matches_second_team)
            {
                matches_fitrst_team.Add(item);
            }
            team.Match1 = matches_fitrst_team;
            return View(team);
        }

        // GET: Teams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,description,logo,available")] Team team, HttpPostedFileBase uploadImage)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid && uploadImage != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                team.logo = imageData;
                db.Team.Add(team);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(team);
        }

        // GET: Teams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Team.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        public ActionResult getImage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Team.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,description,logo,available")] Team team, HttpPostedFileBase uploadImage)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid && uploadImage != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                team.logo = imageData;
                db.Team.Add(team);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Team.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            Team team = db.Team.Find(id);
            db.Team.Remove(team);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Покупка билетов", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>                    
                    <li>@Html.ActionLink("Команды", "Index", "Teams")</li>
                    <li>@Html.ActionLink("Матчи", "Index", "Matches")</li>
                    <li>@if (User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Корзина", "MyOrders", "Orders")
                    }
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/getFiveArticles.cshtml
@model List<tickets.Models.Article>
@{
    Layout = "";
} 




<table class="table">
   @for (int i = 0; i < Model.Count();i++)
    {
        <tr>
            <h2>
                <p>
                    @Html.DisplayFor(modelItem => Model[i].title)
                </p>
            </h2>
            <p>
                @Html.DisplayFor(modelItem => Model[i].annonce)
            </p>            
            <p>
                @Html.DisplayFor(modelItem => Model[i].date)
            </p>
            <p>
                @if (User.IsInRole("Admin")) {
                   @Html.ActionLink("Edit", "Edit", new { id = Model[i].id });
                   @Html.ActionLink("Delete", "Delete", new { id = Model[i].id });
                }
                @Html.ActionLink("Подробно", "Details", new { id = Model[i].id })
            </p>
        </tr>
    }

</table>

Views/Shared/getFiveMathes.cshtml
@model List<tickets.Models.Match>
@{
    Layout = "";
} 



@Html.Raw("<style>#MatchBar {position: fixed; z - index: 101;}</style>")




<article id="MatchBar" >
    <table class="table">
        
        @foreach (var item in Model)
        {
            <tr>
                <td style="cursor:pointer" onMouseOver="this.style.background='#FFCC33'" onMouseOut="this.style.background=''" onClick="document.location='Orders/Create/@item.id'">
                    <p>
                        <h3>

                            @Html.DisplayFor(modelItem => item.date)

                        </h3>
                    </p>
                    <p>
                        @Html.Action("getImage", "Teams", new { id = item.firts_team })
                        <strong>VS</strong>
                        @Html.Action("getImage", "Teams", new { id = item.second_team })
                    </p>
                    <p>
                        @if (User.IsInRole("Admin"))
                    {
                            @Html.ActionLink("Edit", "Edit", new { id = item.id });
                            @Html.ActionLink("Delete", "Delete", new { id = item.id });


                        }
                   

               </td>
            </tr>
        }

    </table>
</article>

Views/Shared/getImage.cshtml
@model tickets.Models.Team

@{
    Layout = "";
} 

    @Html.Raw("<img style='width:80px; height:80px;' src=\"data:image/jpeg;base64,"
                                              + Convert.ToBase64String(Model.logo) + "\" />")

Views/Shared/getMatchById.cshtml
@model tickets.Models.Match
@{
    Layout = "";
} 


        <p>
            <strong>

                @Html.DisplayFor(modelItem => Model.date)

            </strong>
       </p>
<p>
    @Html.Action("getImage", "Teams", new { id = Model.firts_team })
    <strong>VS</strong>
    @Html.Action("getImage", "Teams", new { id = Model.second_team })
</p>
<p>